machine:
  name: fabric_cnc_v1
  units: mm
  planner:
    max_accel: {x: 100, y: 100, z: 50, a: 300}
    junction_deviation: 0.05
    segment_tolerance: 0.05
  gpio:
    use_pigpio: true
  axes:
    X: {step: 24, dir: 23, ena: 9, invert_dir: true, steps_per_mm: 80, hall: 16}
    Y1: {step: 22, dir: 27, ena: 17, invert_dir: true, steps_per_mm: 80, hall: 1}
    Y2: {step: 6, dir: 5, ena: 10, invert_dir: false, steps_per_mm: 80, hall: 20}
    Z: {step: 18, dir: 7, ena: 8, invert_dir: false, steps_per_mm: 400, hall: 25}
    A: {step: 26, dir: 19, ena: 13, invert_dir: true, steps_per_deg: 10, hall: 12}
  limits:
    X: {min: 0, max: 1727}
    Y: {min: 0, max: 1143}
    Z: {min: 0, max: 63.5}
    A: {min: -9999, max: 9999}
  motion:
    default_speed: 20
    max_speed: 100
    default_accel: 100
    lift_height: 25.4
  homing:
    offset: 5
    verification_distance: 10
    speeds:
      X: 10
      Y: 10
      Z: 5
      A: 30 