; Fabric CNC Toolpath
; Generated by ToolpathGenerator

G20 ; Set units to inches
G90 ; Set absolute positioning
G28 ; Home all axes

G0 Z-0.5 ; Move to safe height

; Shape: merged_shape_0
G0 X1.000 Y16.906 ; Move to start
G0 A18.237 ; Set initial cutting wheel angle
G0 Z-1.0 ; Plunge to cutting height
G0 A18.237 ; Rotate Z for cutting direction
G1 X1.018 Y16.852 F1000.0 ; Cut to next point
G0 A18.226 ; Rotate Z for cutting direction
G1 X1.036 Y16.797 F1000.0 ; Cut to next point
G0 A18.205 ; Rotate Z for cutting direction
G1 X1.054 Y16.743 F1000.0 ; Cut to next point
G0 A18.173 ; Rotate Z for cutting direction
G1 X1.071 Y16.689 F1000.0 ; Cut to next point
G0 A18.131 ; Rotate Z for cutting direction
G1 X1.089 Y16.635 F1000.0 ; Cut to next point
G0 A18.078 ; Rotate Z for cutting direction
G1 X1.107 Y16.580 F1000.0 ; Cut to next point
G0 A18.014 ; Rotate Z for cutting direction
G1 X1.125 Y16.526 F1000.0 ; Cut to next point
G0 A17.940 ; Rotate Z for cutting direction
G1 X1.142 Y16.472 F1000.0 ; Cut to next point
G0 A17.855 ; Rotate Z for cutting direction
G1 X1.160 Y16.417 F1000.0 ; Cut to next point
G0 A17.760 ; Rotate Z for cutting direction
G1 X1.177 Y16.363 F1000.0 ; Cut to next point
G0 A17.653 ; Rotate Z for cutting direction
G1 X1.194 Y16.309 F1000.0 ; Cut to next point
G0 A17.537 ; Rotate Z for cutting direction
G1 X1.212 Y16.254 F1000.0 ; Cut to next point
G0 A17.409 ; Rotate Z for cutting direction
G1 X1.229 Y16.200 F1000.0 ; Cut to next point
G0 A17.271 ; Rotate Z for cutting direction
G1 X1.246 Y16.145 F1000.0 ; Cut to next point
G0 A17.123 ; Rotate Z for cutting direction
G1 X1.262 Y16.091 F1000.0 ; Cut to next point
G0 A16.963 ; Rotate Z for cutting direction
G1 X1.279 Y16.036 F1000.0 ; Cut to next point
G0 A16.794 ; Rotate Z for cutting direction
G1 X1.295 Y15.982 F1000.0 ; Cut to next point
G0 A16.613 ; Rotate Z for cutting direction
G1 X1.312 Y15.927 F1000.0 ; Cut to next point
G0 A16.422 ; Rotate Z for cutting direction
G1 X1.328 Y15.872 F1000.0 ; Cut to next point
G0 A16.220 ; Rotate Z for cutting direction
G1 X1.344 Y15.817 F1000.0 ; Cut to next point
G0 A16.008 ; Rotate Z for cutting direction
G1 X1.360 Y15.762 F1000.0 ; Cut to next point
G0 A15.785 ; Rotate Z for cutting direction
G1 X1.375 Y15.708 F1000.0 ; Cut to next point
G0 A15.554 ; Rotate Z for cutting direction
G1 X1.390 Y15.653 F1000.0 ; Cut to next point
G0 A15.337 ; Rotate Z for cutting direction
G1 X1.405 Y15.598 F1000.0 ; Cut to next point
G0 A15.150 ; Rotate Z for cutting direction
G1 X1.420 Y15.542 F1000.0 ; Cut to next point
G0 A14.985 ; Rotate Z for cutting direction
G1 X1.435 Y15.487 F1000.0 ; Cut to next point
G0 A14.826 ; Rotate Z for cutting direction
G1 X1.450 Y15.432 F1000.0 ; Cut to next point
G0 A14.666 ; Rotate Z for cutting direction
G1 X1.464 Y15.377 F1000.0 ; Cut to next point
G0 A14.506 ; Rotate Z for cutting direction
G1 X1.479 Y15.322 F1000.0 ; Cut to next point
G0 A14.346 ; Rotate Z for cutting direction
G1 X1.493 Y15.266 F1000.0 ; Cut to next point
G0 A14.185 ; Rotate Z for cutting direction
G1 X1.507 Y15.211 F1000.0 ; Cut to next point
G0 A14.025 ; Rotate Z for cutting direction
G1 X1.520 Y15.156 F1000.0 ; Cut to next point
G0 A13.864 ; Rotate Z for cutting direction
G1 X1.534 Y15.100 F1000.0 ; Cut to next point
G0 A13.703 ; Rotate Z for cutting direction
G1 X1.548 Y15.045 F1000.0 ; Cut to next point
G0 A13.542 ; Rotate Z for cutting direction
G1 X1.561 Y14.989 F1000.0 ; Cut to next point
G0 A13.380 ; Rotate Z for cutting direction
G1 X1.574 Y14.934 F1000.0 ; Cut to next point
G0 A13.218 ; Rotate Z for cutting direction
G1 X1.587 Y14.878 F1000.0 ; Cut to next point
G0 A13.056 ; Rotate Z for cutting direction
G1 X1.600 Y14.823 F1000.0 ; Cut to next point
G0 A12.894 ; Rotate Z for cutting direction
G1 X1.613 Y14.767 F1000.0 ; Cut to next point
G0 A12.732 ; Rotate Z for cutting direction
G1 X1.626 Y14.711 F1000.0 ; Cut to next point
G0 A12.569 ; Rotate Z for cutting direction
G1 X1.638 Y14.656 F1000.0 ; Cut to next point
G0 A12.406 ; Rotate Z for cutting direction
G1 X1.650 Y14.600 F1000.0 ; Cut to next point
G0 A12.243 ; Rotate Z for cutting direction
G1 X1.662 Y14.544 F1000.0 ; Cut to next point
G0 A12.080 ; Rotate Z for cutting direction
G1 X1.674 Y14.488 F1000.0 ; Cut to next point
G0 A11.916 ; Rotate Z for cutting direction
G1 X1.686 Y14.432 F1000.0 ; Cut to next point
G0 A11.752 ; Rotate Z for cutting direction
G1 X1.698 Y14.376 F1000.0 ; Cut to next point
G0 A11.588 ; Rotate Z for cutting direction
G1 X1.709 Y14.321 F1000.0 ; Cut to next point
G0 A11.424 ; Rotate Z for cutting direction
G1 X1.720 Y14.265 F1000.0 ; Cut to next point
G0 A11.260 ; Rotate Z for cutting direction
G1 X1.732 Y14.209 F1000.0 ; Cut to next point
G0 A11.095 ; Rotate Z for cutting direction
G1 X1.743 Y14.153 F1000.0 ; Cut to next point
G0 A10.930 ; Rotate Z for cutting direction
G1 X1.753 Y14.097 F1000.0 ; Cut to next point
G0 A10.765 ; Rotate Z for cutting direction
G1 X1.764 Y14.040 F1000.0 ; Cut to next point
G0 A10.600 ; Rotate Z for cutting direction
G1 X1.775 Y13.984 F1000.0 ; Cut to next point
G0 A10.436 ; Rotate Z for cutting direction
G1 X1.785 Y13.928 F1000.0 ; Cut to next point
G0 A10.271 ; Rotate Z for cutting direction
G1 X1.795 Y13.872 F1000.0 ; Cut to next point
G0 A10.107 ; Rotate Z for cutting direction
G1 X1.805 Y13.816 F1000.0 ; Cut to next point
G0 A9.943 ; Rotate Z for cutting direction
G1 X1.815 Y13.760 F1000.0 ; Cut to next point
G0 A9.779 ; Rotate Z for cutting direction
G1 X1.825 Y13.703 F1000.0 ; Cut to next point
G0 A9.615 ; Rotate Z for cutting direction
G1 X1.834 Y13.647 F1000.0 ; Cut to next point
G0 A9.451 ; Rotate Z for cutting direction
G1 X1.844 Y13.591 F1000.0 ; Cut to next point
G0 A9.288 ; Rotate Z for cutting direction
G1 X1.853 Y13.534 F1000.0 ; Cut to next point
G0 A9.124 ; Rotate Z for cutting direction
G1 X1.862 Y13.478 F1000.0 ; Cut to next point
G0 A8.961 ; Rotate Z for cutting direction
G1 X1.871 Y13.422 F1000.0 ; Cut to next point
G0 A8.798 ; Rotate Z for cutting direction
G1 X1.879 Y13.365 F1000.0 ; Cut to next point
G0 A8.635 ; Rotate Z for cutting direction
G1 X1.888 Y13.309 F1000.0 ; Cut to next point
G0 A8.472 ; Rotate Z for cutting direction
G1 X1.896 Y13.252 F1000.0 ; Cut to next point
G0 A8.309 ; Rotate Z for cutting direction
G1 X1.905 Y13.196 F1000.0 ; Cut to next point
G0 A8.146 ; Rotate Z for cutting direction
G1 X1.913 Y13.140 F1000.0 ; Cut to next point
G0 A7.983 ; Rotate Z for cutting direction
G1 X1.921 Y13.083 F1000.0 ; Cut to next point
G0 A7.819 ; Rotate Z for cutting direction
G1 X1.928 Y13.026 F1000.0 ; Cut to next point
G0 A7.655 ; Rotate Z for cutting direction
G1 X1.936 Y12.970 F1000.0 ; Cut to next point
G0 A7.491 ; Rotate Z for cutting direction
G1 X1.943 Y12.913 F1000.0 ; Cut to next point
G0 A7.327 ; Rotate Z for cutting direction
G1 X1.951 Y12.857 F1000.0 ; Cut to next point
G0 A7.162 ; Rotate Z for cutting direction
G1 X1.958 Y12.800 F1000.0 ; Cut to next point
G0 A6.997 ; Rotate Z for cutting direction
G1 X1.965 Y12.743 F1000.0 ; Cut to next point
G0 A6.835 ; Rotate Z for cutting direction
G1 X1.972 Y12.687 F1000.0 ; Cut to next point
G0 A6.687 ; Rotate Z for cutting direction
G1 X1.978 Y12.630 F1000.0 ; Cut to next point
G0 A6.541 ; Rotate Z for cutting direction
G1 X1.985 Y12.573 F1000.0 ; Cut to next point
G0 A6.388 ; Rotate Z for cutting direction
G1 X1.991 Y12.517 F1000.0 ; Cut to next point
G0 A6.229 ; Rotate Z for cutting direction
G1 X1.997 Y12.460 F1000.0 ; Cut to next point
G0 A6.064 ; Rotate Z for cutting direction
G1 X2.003 Y12.403 F1000.0 ; Cut to next point
G0 A5.893 ; Rotate Z for cutting direction
G1 X2.009 Y12.346 F1000.0 ; Cut to next point
G0 A5.715 ; Rotate Z for cutting direction
G1 X2.015 Y12.290 F1000.0 ; Cut to next point
G0 A5.531 ; Rotate Z for cutting direction
G1 X2.020 Y12.233 F1000.0 ; Cut to next point
G0 A5.340 ; Rotate Z for cutting direction
G1 X2.026 Y12.176 F1000.0 ; Cut to next point
G0 A5.144 ; Rotate Z for cutting direction
G1 X2.031 Y12.119 F1000.0 ; Cut to next point
G0 A4.941 ; Rotate Z for cutting direction
G1 X2.036 Y12.062 F1000.0 ; Cut to next point
G0 A4.732 ; Rotate Z for cutting direction
G1 X2.040 Y12.005 F1000.0 ; Cut to next point
G0 A4.530 ; Rotate Z for cutting direction
G1 X2.045 Y11.949 F1000.0 ; Cut to next point
G0 A4.345 ; Rotate Z for cutting direction
G1 X2.049 Y11.892 F1000.0 ; Cut to next point
G0 A4.176 ; Rotate Z for cutting direction
G1 X2.053 Y11.835 F1000.0 ; Cut to next point
G0 A4.025 ; Rotate Z for cutting direction
G1 X2.057 Y11.778 F1000.0 ; Cut to next point
G0 A3.890 ; Rotate Z for cutting direction
G1 X2.061 Y11.721 F1000.0 ; Cut to next point
G0 A3.772 ; Rotate Z for cutting direction
G1 X2.065 Y11.664 F1000.0 ; Cut to next point
G0 A3.671 ; Rotate Z for cutting direction
G1 X2.069 Y11.607 F1000.0 ; Cut to next point
G0 A3.586 ; Rotate Z for cutting direction
G1 X2.072 Y11.550 F1000.0 ; Cut to next point
G0 A3.519 ; Rotate Z for cutting direction
G1 X2.076 Y11.493 F1000.0 ; Cut to next point
G0 A3.469 ; Rotate Z for cutting direction
G1 X2.079 Y11.436 F1000.0 ; Cut to next point
G0 A3.435 ; Rotate Z for cutting direction
G1 X2.083 Y11.379 F1000.0 ; Cut to next point
G0 A3.418 ; Rotate Z for cutting direction
G1 X2.086 Y11.322 F1000.0 ; Cut to next point
G0 A4.034 ; Rotate Z for cutting direction
G1 X2.090 Y11.268 F1000.0 ; Cut to next point
G0 A4.047 ; Rotate Z for cutting direction
G1 X2.094 Y11.213 F1000.0 ; Cut to next point
G0 A4.074 ; Rotate Z for cutting direction
G1 X2.098 Y11.159 F1000.0 ; Cut to next point
G0 A4.115 ; Rotate Z for cutting direction
G1 X2.102 Y11.104 F1000.0 ; Cut to next point
G0 A4.168 ; Rotate Z for cutting direction
G1 X2.106 Y11.050 F1000.0 ; Cut to next point
G0 A4.235 ; Rotate Z for cutting direction
G1 X2.110 Y10.995 F1000.0 ; Cut to next point
G0 A4.316 ; Rotate Z for cutting direction
G1 X2.114 Y10.941 F1000.0 ; Cut to next point
G0 A4.410 ; Rotate Z for cutting direction
G1 X2.118 Y10.886 F1000.0 ; Cut to next point
G0 A4.518 ; Rotate Z for cutting direction
G1 X2.122 Y10.832 F1000.0 ; Cut to next point
G0 A4.639 ; Rotate Z for cutting direction
G1 X2.127 Y10.777 F1000.0 ; Cut to next point
G0 A4.773 ; Rotate Z for cutting direction
G1 X2.131 Y10.723 F1000.0 ; Cut to next point
G0 A4.921 ; Rotate Z for cutting direction
G1 X2.136 Y10.669 F1000.0 ; Cut to next point
G0 A5.083 ; Rotate Z for cutting direction
G1 X2.141 Y10.614 F1000.0 ; Cut to next point
G0 A5.257 ; Rotate Z for cutting direction
G1 X2.146 Y10.560 F1000.0 ; Cut to next point
G0 A5.446 ; Rotate Z for cutting direction
G1 X2.151 Y10.505 F1000.0 ; Cut to next point
G0 A5.648 ; Rotate Z for cutting direction
G1 X2.156 Y10.451 F1000.0 ; Cut to next point
G0 A5.863 ; Rotate Z for cutting direction
G1 X2.162 Y10.397 F1000.0 ; Cut to next point
G0 A6.092 ; Rotate Z for cutting direction
G1 X2.168 Y10.343 F1000.0 ; Cut to next point
G0 A6.334 ; Rotate Z for cutting direction
G1 X2.174 Y10.288 F1000.0 ; Cut to next point
G0 A6.590 ; Rotate Z for cutting direction
G1 X2.180 Y10.234 F1000.0 ; Cut to next point
G0 A6.859 ; Rotate Z for cutting direction
G1 X2.186 Y10.180 F1000.0 ; Cut to next point
G0 A7.136 ; Rotate Z for cutting direction
G1 X2.193 Y10.126 F1000.0 ; Cut to next point
G0 A7.406 ; Rotate Z for cutting direction
G1 X2.200 Y10.072 F1000.0 ; Cut to next point
G0 A7.668 ; Rotate Z for cutting direction
G1 X2.207 Y10.017 F1000.0 ; Cut to next point
G0 A7.922 ; Rotate Z for cutting direction
G1 X2.215 Y9.963 F1000.0 ; Cut to next point
G0 A8.168 ; Rotate Z for cutting direction
G1 X2.223 Y9.909 F1000.0 ; Cut to next point
G0 A8.405 ; Rotate Z for cutting direction
G1 X2.231 Y9.855 F1000.0 ; Cut to next point
G0 A8.633 ; Rotate Z for cutting direction
G1 X2.239 Y9.801 F1000.0 ; Cut to next point
G0 A8.854 ; Rotate Z for cutting direction
G1 X2.247 Y9.747 F1000.0 ; Cut to next point
G0 A9.066 ; Rotate Z for cutting direction
G1 X2.256 Y9.693 F1000.0 ; Cut to next point
G0 A9.270 ; Rotate Z for cutting direction
G1 X2.265 Y9.640 F1000.0 ; Cut to next point
G0 A9.465 ; Rotate Z for cutting direction
G1 X2.274 Y9.586 F1000.0 ; Cut to next point
G0 A9.656 ; Rotate Z for cutting direction
G1 X2.283 Y9.532 F1000.0 ; Cut to next point
G0 A9.847 ; Rotate Z for cutting direction
G1 X2.292 Y9.478 F1000.0 ; Cut to next point
G0 A10.042 ; Rotate Z for cutting direction
G1 X2.302 Y9.424 F1000.0 ; Cut to next point
G0 A10.238 ; Rotate Z for cutting direction
G1 X2.311 Y9.371 F1000.0 ; Cut to next point
G0 A10.437 ; Rotate Z for cutting direction
G1 X2.321 Y9.317 F1000.0 ; Cut to next point
G0 A10.638 ; Rotate Z for cutting direction
G1 X2.331 Y9.263 F1000.0 ; Cut to next point
G0 A10.842 ; Rotate Z for cutting direction
G1 X2.342 Y9.210 F1000.0 ; Cut to next point
G0 A11.048 ; Rotate Z for cutting direction
G1 X2.352 Y9.156 F1000.0 ; Cut to next point
G0 A11.256 ; Rotate Z for cutting direction
G1 X2.363 Y9.102 F1000.0 ; Cut to next point
G0 A11.467 ; Rotate Z for cutting direction
G1 X2.374 Y9.049 F1000.0 ; Cut to next point
G0 A11.679 ; Rotate Z for cutting direction
G1 X2.385 Y8.995 F1000.0 ; Cut to next point
G0 A11.891 ; Rotate Z for cutting direction
G1 X2.396 Y8.942 F1000.0 ; Cut to next point
G0 A12.102 ; Rotate Z for cutting direction
G1 X2.407 Y8.889 F1000.0 ; Cut to next point
G0 A12.314 ; Rotate Z for cutting direction
G1 X2.419 Y8.835 F1000.0 ; Cut to next point
G0 A12.525 ; Rotate Z for cutting direction
G1 X2.431 Y8.782 F1000.0 ; Cut to next point
G0 A12.736 ; Rotate Z for cutting direction
G1 X2.443 Y8.729 F1000.0 ; Cut to next point
G0 A12.946 ; Rotate Z for cutting direction
G1 X2.455 Y8.675 F1000.0 ; Cut to next point
G0 A13.157 ; Rotate Z for cutting direction
G1 X2.468 Y8.622 F1000.0 ; Cut to next point
G0 A13.367 ; Rotate Z for cutting direction
G1 X2.480 Y8.569 F1000.0 ; Cut to next point
G0 A13.577 ; Rotate Z for cutting direction
G1 X2.493 Y8.516 F1000.0 ; Cut to next point
G0 A13.787 ; Rotate Z for cutting direction
G1 X2.506 Y8.463 F1000.0 ; Cut to next point
G0 A13.996 ; Rotate Z for cutting direction
G1 X2.519 Y8.410 F1000.0 ; Cut to next point
G0 A14.206 ; Rotate Z for cutting direction
G1 X2.533 Y8.357 F1000.0 ; Cut to next point
G0 A14.415 ; Rotate Z for cutting direction
G1 X2.546 Y8.304 F1000.0 ; Cut to next point
G0 A14.623 ; Rotate Z for cutting direction
G1 X2.560 Y8.251 F1000.0 ; Cut to next point
G0 A14.832 ; Rotate Z for cutting direction
G1 X2.574 Y8.198 F1000.0 ; Cut to next point
G0 A15.041 ; Rotate Z for cutting direction
G1 X2.588 Y8.146 F1000.0 ; Cut to next point
G0 A15.249 ; Rotate Z for cutting direction
G1 X2.603 Y8.093 F1000.0 ; Cut to next point
G0 A15.457 ; Rotate Z for cutting direction
G1 X2.617 Y8.040 F1000.0 ; Cut to next point
G0 A15.665 ; Rotate Z for cutting direction
G1 X2.632 Y7.988 F1000.0 ; Cut to next point
G0 A15.873 ; Rotate Z for cutting direction
G1 X2.647 Y7.935 F1000.0 ; Cut to next point
G0 A16.080 ; Rotate Z for cutting direction
G1 X2.662 Y7.883 F1000.0 ; Cut to next point
G0 A16.288 ; Rotate Z for cutting direction
G1 X2.677 Y7.830 F1000.0 ; Cut to next point
G0 A16.496 ; Rotate Z for cutting direction
G1 X2.693 Y7.778 F1000.0 ; Cut to next point
G0 A16.704 ; Rotate Z for cutting direction
G1 X2.708 Y7.726 F1000.0 ; Cut to next point
G0 A16.912 ; Rotate Z for cutting direction
G1 X2.724 Y7.673 F1000.0 ; Cut to next point
G0 A17.120 ; Rotate Z for cutting direction
G1 X2.740 Y7.621 F1000.0 ; Cut to next point
G0 A17.328 ; Rotate Z for cutting direction
G1 X2.757 Y7.569 F1000.0 ; Cut to next point
G0 A17.536 ; Rotate Z for cutting direction
G1 X2.773 Y7.517 F1000.0 ; Cut to next point
G0 A17.744 ; Rotate Z for cutting direction
G1 X2.790 Y7.465 F1000.0 ; Cut to next point
G0 A17.953 ; Rotate Z for cutting direction
G1 X2.807 Y7.413 F1000.0 ; Cut to next point
G0 A18.161 ; Rotate Z for cutting direction
G1 X2.824 Y7.361 F1000.0 ; Cut to next point
G0 A18.370 ; Rotate Z for cutting direction
G1 X2.841 Y7.309 F1000.0 ; Cut to next point
G0 A18.579 ; Rotate Z for cutting direction
G1 X2.858 Y7.258 F1000.0 ; Cut to next point
G0 A18.787 ; Rotate Z for cutting direction
G1 X2.876 Y7.206 F1000.0 ; Cut to next point
G0 A18.996 ; Rotate Z for cutting direction
G1 X2.894 Y7.154 F1000.0 ; Cut to next point
G0 A19.205 ; Rotate Z for cutting direction
G1 X2.912 Y7.103 F1000.0 ; Cut to next point
G0 A19.414 ; Rotate Z for cutting direction
G1 X2.930 Y7.051 F1000.0 ; Cut to next point
G0 A19.623 ; Rotate Z for cutting direction
G1 X2.948 Y7.000 F1000.0 ; Cut to next point
G0 A19.831 ; Rotate Z for cutting direction
G1 X2.967 Y6.949 F1000.0 ; Cut to next point
G0 A20.040 ; Rotate Z for cutting direction
G1 X2.985 Y6.897 F1000.0 ; Cut to next point
G0 A20.250 ; Rotate Z for cutting direction
G1 X3.004 Y6.846 F1000.0 ; Cut to next point
G0 A20.462 ; Rotate Z for cutting direction
G1 X3.023 Y6.795 F1000.0 ; Cut to next point
G0 A20.673 ; Rotate Z for cutting direction
G1 X3.043 Y6.744 F1000.0 ; Cut to next point
G0 A20.884 ; Rotate Z for cutting direction
G1 X3.062 Y6.693 F1000.0 ; Cut to next point
G0 A21.094 ; Rotate Z for cutting direction
G1 X3.082 Y6.642 F1000.0 ; Cut to next point
G0 A21.303 ; Rotate Z for cutting direction
G1 X3.102 Y6.591 F1000.0 ; Cut to next point
G0 A21.512 ; Rotate Z for cutting direction
G1 X3.122 Y6.540 F1000.0 ; Cut to next point
G0 A21.720 ; Rotate Z for cutting direction
G1 X3.142 Y6.489 F1000.0 ; Cut to next point
G0 A21.927 ; Rotate Z for cutting direction
G1 X3.162 Y6.439 F1000.0 ; Cut to next point
G0 A22.134 ; Rotate Z for cutting direction
G1 X3.183 Y6.388 F1000.0 ; Cut to next point
G0 A22.341 ; Rotate Z for cutting direction
G1 X3.203 Y6.338 F1000.0 ; Cut to next point
G0 A22.547 ; Rotate Z for cutting direction
G1 X3.224 Y6.287 F1000.0 ; Cut to next point
G0 A22.752 ; Rotate Z for cutting direction
G1 X3.246 Y6.237 F1000.0 ; Cut to next point
G0 A22.957 ; Rotate Z for cutting direction
G1 X3.267 Y6.187 F1000.0 ; Cut to next point
G0 A23.161 ; Rotate Z for cutting direction
G1 X3.288 Y6.136 F1000.0 ; Cut to next point
G0 A23.364 ; Rotate Z for cutting direction
G1 X3.310 Y6.086 F1000.0 ; Cut to next point
G0 A23.567 ; Rotate Z for cutting direction
G1 X3.332 Y6.036 F1000.0 ; Cut to next point
G0 A23.770 ; Rotate Z for cutting direction
G1 X3.354 Y5.986 F1000.0 ; Cut to next point
G0 A23.972 ; Rotate Z for cutting direction
G1 X3.376 Y5.936 F1000.0 ; Cut to next point
G0 A24.188 ; Rotate Z for cutting direction
G1 X3.398 Y5.886 F1000.0 ; Cut to next point
G0 A24.442 ; Rotate Z for cutting direction
G1 X3.421 Y5.837 F1000.0 ; Cut to next point
G0 A24.732 ; Rotate Z for cutting direction
G1 X3.444 Y5.787 F1000.0 ; Cut to next point
G0 A25.022 ; Rotate Z for cutting direction
G1 X3.467 Y5.738 F1000.0 ; Cut to next point
G0 A25.298 ; Rotate Z for cutting direction
G1 X3.490 Y5.688 F1000.0 ; Cut to next point
G0 A25.559 ; Rotate Z for cutting direction
G1 X3.514 Y5.639 F1000.0 ; Cut to next point
G0 A25.806 ; Rotate Z for cutting direction
G1 X3.538 Y5.590 F1000.0 ; Cut to next point
G0 A26.038 ; Rotate Z for cutting direction
G1 X3.562 Y5.541 F1000.0 ; Cut to next point
G0 A26.256 ; Rotate Z for cutting direction
G1 X3.586 Y5.492 F1000.0 ; Cut to next point
G0 A26.459 ; Rotate Z for cutting direction
G1 X3.610 Y5.443 F1000.0 ; Cut to next point
G0 A26.648 ; Rotate Z for cutting direction
G1 X3.634 Y5.394 F1000.0 ; Cut to next point
G0 A26.822 ; Rotate Z for cutting direction
G1 X3.659 Y5.346 F1000.0 ; Cut to next point
G0 A26.981 ; Rotate Z for cutting direction
G1 X3.684 Y5.297 F1000.0 ; Cut to next point
G0 A27.126 ; Rotate Z for cutting direction
G1 X3.709 Y5.248 F1000.0 ; Cut to next point
G0 A27.257 ; Rotate Z for cutting direction
G1 X3.734 Y5.200 F1000.0 ; Cut to next point
G0 A27.373 ; Rotate Z for cutting direction
G1 X3.759 Y5.151 F1000.0 ; Cut to next point
G0 A27.474 ; Rotate Z for cutting direction
G1 X3.784 Y5.103 F1000.0 ; Cut to next point
G0 A27.561 ; Rotate Z for cutting direction
G1 X3.809 Y5.054 F1000.0 ; Cut to next point
G0 A27.634 ; Rotate Z for cutting direction
G1 X3.835 Y5.006 F1000.0 ; Cut to next point
G0 A27.692 ; Rotate Z for cutting direction
G1 X3.860 Y4.958 F1000.0 ; Cut to next point
G0 A27.736 ; Rotate Z for cutting direction
G1 X3.886 Y4.909 F1000.0 ; Cut to next point
G0 A27.765 ; Rotate Z for cutting direction
G1 X3.911 Y4.861 F1000.0 ; Cut to next point
G0 A27.779 ; Rotate Z for cutting direction
G1 X3.936 Y4.813 F1000.0 ; Cut to next point
G0 A29.534 ; Rotate Z for cutting direction
G1 X3.963 Y4.765 F1000.0 ; Cut to next point
G0 A29.560 ; Rotate Z for cutting direction
G1 X3.991 Y4.717 F1000.0 ; Cut to next point
G0 A29.612 ; Rotate Z for cutting direction
G1 X4.018 Y4.669 F1000.0 ; Cut to next point
G0 A29.689 ; Rotate Z for cutting direction
G1 X4.045 Y4.622 F1000.0 ; Cut to next point
G0 A29.792 ; Rotate Z for cutting direction
G1 X4.072 Y4.574 F1000.0 ; Cut to next point
G0 A29.920 ; Rotate Z for cutting direction
G1 X4.099 Y4.527 F1000.0 ; Cut to next point
G0 A30.074 ; Rotate Z for cutting direction
G1 X4.127 Y4.479 F1000.0 ; Cut to next point
G0 A30.254 ; Rotate Z for cutting direction
G1 X4.155 Y4.432 F1000.0 ; Cut to next point
G0 A30.459 ; Rotate Z for cutting direction
G1 X4.182 Y4.385 F1000.0 ; Cut to next point
G0 A30.690 ; Rotate Z for cutting direction
G1 X4.210 Y4.337 F1000.0 ; Cut to next point
G0 A30.945 ; Rotate Z for cutting direction
G1 X4.238 Y4.290 F1000.0 ; Cut to next point
G0 A31.205 ; Rotate Z for cutting direction
G1 X4.267 Y4.243 F1000.0 ; Cut to next point
G0 A31.459 ; Rotate Z for cutting direction
G1 X4.296 Y4.197 F1000.0 ; Cut to next point
G0 A31.706 ; Rotate Z for cutting direction
G1 X4.324 Y4.150 F1000.0 ; Cut to next point
G0 A31.947 ; Rotate Z for cutting direction
G1 X4.353 Y4.104 F1000.0 ; Cut to next point
G0 A32.181 ; Rotate Z for cutting direction
G1 X4.383 Y4.057 F1000.0 ; Cut to next point
G0 A32.408 ; Rotate Z for cutting direction
G1 X4.412 Y4.011 F1000.0 ; Cut to next point
G0 A32.629 ; Rotate Z for cutting direction
G1 X4.442 Y3.965 F1000.0 ; Cut to next point
G0 A32.843 ; Rotate Z for cutting direction
G1 X4.471 Y3.919 F1000.0 ; Cut to next point
G0 A33.051 ; Rotate Z for cutting direction
G1 X4.501 Y3.873 F1000.0 ; Cut to next point
G0 A33.252 ; Rotate Z for cutting direction
G1 X4.531 Y3.827 F1000.0 ; Cut to next point
G0 A33.449 ; Rotate Z for cutting direction
G1 X4.561 Y3.781 F1000.0 ; Cut to next point
G0 A33.646 ; Rotate Z for cutting direction
G1 X4.592 Y3.735 F1000.0 ; Cut to next point
G0 A33.845 ; Rotate Z for cutting direction
G1 X4.622 Y3.690 F1000.0 ; Cut to next point
G0 A34.045 ; Rotate Z for cutting direction
G1 X4.653 Y3.644 F1000.0 ; Cut to next point
G0 A34.247 ; Rotate Z for cutting direction
G1 X4.684 Y3.599 F1000.0 ; Cut to next point
G0 A34.450 ; Rotate Z for cutting direction
G1 X4.715 Y3.554 F1000.0 ; Cut to next point
G0 A34.655 ; Rotate Z for cutting direction
G1 X4.746 Y3.509 F1000.0 ; Cut to next point
G0 A34.861 ; Rotate Z for cutting direction
G1 X4.778 Y3.464 F1000.0 ; Cut to next point
G0 A35.069 ; Rotate Z for cutting direction
G1 X4.809 Y3.419 F1000.0 ; Cut to next point
G0 A35.278 ; Rotate Z for cutting direction
G1 X4.841 Y3.374 F1000.0 ; Cut to next point
G0 A35.489 ; Rotate Z for cutting direction
G1 X4.873 Y3.329 F1000.0 ; Cut to next point
G0 A35.701 ; Rotate Z for cutting direction
G1 X4.905 Y3.285 F1000.0 ; Cut to next point
G0 A35.914 ; Rotate Z for cutting direction
G1 X4.937 Y3.240 F1000.0 ; Cut to next point
G0 A36.130 ; Rotate Z for cutting direction
G1 X4.969 Y3.196 F1000.0 ; Cut to next point
G0 A36.342 ; Rotate Z for cutting direction
G1 X5.002 Y3.152 F1000.0 ; Cut to next point
G0 A36.551 ; Rotate Z for cutting direction
G1 X5.034 Y3.108 F1000.0 ; Cut to next point
G0 A36.760 ; Rotate Z for cutting direction
G1 X5.067 Y3.064 F1000.0 ; Cut to next point
G0 A36.970 ; Rotate Z for cutting direction
G1 X5.100 Y3.020 F1000.0 ; Cut to next point
G0 A37.179 ; Rotate Z for cutting direction
G1 X5.133 Y2.976 F1000.0 ; Cut to next point
G0 A37.388 ; Rotate Z for cutting direction
G1 X5.166 Y2.933 F1000.0 ; Cut to next point
G0 A37.598 ; Rotate Z for cutting direction
G1 X5.200 Y2.889 F1000.0 ; Cut to next point
G0 A37.807 ; Rotate Z for cutting direction
G1 X5.234 Y2.846 F1000.0 ; Cut to next point
G0 A38.017 ; Rotate Z for cutting direction
G1 X5.267 Y2.803 F1000.0 ; Cut to next point
G0 A38.226 ; Rotate Z for cutting direction
G1 X5.301 Y2.760 F1000.0 ; Cut to next point
G0 A38.436 ; Rotate Z for cutting direction
G1 X5.335 Y2.717 F1000.0 ; Cut to next point
G0 A38.645 ; Rotate Z for cutting direction
G1 X5.370 Y2.674 F1000.0 ; Cut to next point
G0 A38.855 ; Rotate Z for cutting direction
G1 X5.404 Y2.631 F1000.0 ; Cut to next point
G0 A39.064 ; Rotate Z for cutting direction
G1 X5.439 Y2.589 F1000.0 ; Cut to next point
G0 A39.274 ; Rotate Z for cutting direction
G1 X5.473 Y2.546 F1000.0 ; Cut to next point
G0 A39.483 ; Rotate Z for cutting direction
G1 X5.508 Y2.504 F1000.0 ; Cut to next point
G0 A39.693 ; Rotate Z for cutting direction
G1 X5.543 Y2.462 F1000.0 ; Cut to next point
G0 A39.902 ; Rotate Z for cutting direction
G1 X5.578 Y2.420 F1000.0 ; Cut to next point
G0 A40.112 ; Rotate Z for cutting direction
G1 X5.614 Y2.378 F1000.0 ; Cut to next point
G0 A40.322 ; Rotate Z for cutting direction
G1 X5.649 Y2.336 F1000.0 ; Cut to next point
G0 A40.531 ; Rotate Z for cutting direction
G1 X5.685 Y2.294 F1000.0 ; Cut to next point
G0 A40.741 ; Rotate Z for cutting direction
G1 X5.721 Y2.253 F1000.0 ; Cut to next point
G0 A40.951 ; Rotate Z for cutting direction
G1 X5.757 Y2.211 F1000.0 ; Cut to next point
G0 A41.161 ; Rotate Z for cutting direction
G1 X5.793 Y2.170 F1000.0 ; Cut to next point
G0 A41.371 ; Rotate Z for cutting direction
G1 X5.829 Y2.129 F1000.0 ; Cut to next point
G0 A41.581 ; Rotate Z for cutting direction
G1 X5.865 Y2.088 F1000.0 ; Cut to next point
G0 A41.791 ; Rotate Z for cutting direction
G1 X5.902 Y2.047 F1000.0 ; Cut to next point
G0 A41.993 ; Rotate Z for cutting direction
G1 X5.939 Y2.006 F1000.0 ; Cut to next point
G0 A42.200 ; Rotate Z for cutting direction
G1 X5.975 Y1.965 F1000.0 ; Cut to next point
G0 A42.474 ; Rotate Z for cutting direction
G1 X6.013 Y1.925 F1000.0 ; Cut to next point
G0 A42.770 ; Rotate Z for cutting direction
G1 X6.050 Y1.885 F1000.0 ; Cut to next point
G0 A43.051 ; Rotate Z for cutting direction
G1 X6.087 Y1.845 F1000.0 ; Cut to next point
G0 A43.316 ; Rotate Z for cutting direction
G1 X6.125 Y1.805 F1000.0 ; Cut to next point
G0 A43.564 ; Rotate Z for cutting direction
G1 X6.163 Y1.765 F1000.0 ; Cut to next point
G0 A43.797 ; Rotate Z for cutting direction
G1 X6.201 Y1.725 F1000.0 ; Cut to next point
G0 A44.013 ; Rotate Z for cutting direction
G1 X6.239 Y1.686 F1000.0 ; Cut to next point
G0 A44.213 ; Rotate Z for cutting direction
G1 X6.277 Y1.647 F1000.0 ; Cut to next point
G0 A44.397 ; Rotate Z for cutting direction
G1 X6.315 Y1.607 F1000.0 ; Cut to next point
G0 A44.564 ; Rotate Z for cutting direction
G1 X6.354 Y1.568 F1000.0 ; Cut to next point
G0 A44.716 ; Rotate Z for cutting direction
G1 X6.392 Y1.529 F1000.0 ; Cut to next point
G0 A44.851 ; Rotate Z for cutting direction
G1 X6.431 Y1.491 F1000.0 ; Cut to next point
G0 A44.970 ; Rotate Z for cutting direction
G1 X6.470 Y1.452 F1000.0 ; Cut to next point
G0 A45.073 ; Rotate Z for cutting direction
G1 X6.509 Y1.413 F1000.0 ; Cut to next point
G0 A45.160 ; Rotate Z for cutting direction
G1 X6.547 Y1.374 F1000.0 ; Cut to next point
G0 A45.230 ; Rotate Z for cutting direction
G1 X6.586 Y1.336 F1000.0 ; Cut to next point
G0 A45.285 ; Rotate Z for cutting direction
G1 X6.625 Y1.297 F1000.0 ; Cut to next point
G0 A45.323 ; Rotate Z for cutting direction
G1 X6.664 Y1.259 F1000.0 ; Cut to next point
G0 A45.345 ; Rotate Z for cutting direction
G1 X6.703 Y1.220 F1000.0 ; Cut to next point
G0 A47.667 ; Rotate Z for cutting direction
G1 X6.756 Y1.172 F1000.0 ; Cut to next point
G0 A52.273 ; Rotate Z for cutting direction
G1 X6.798 Y1.140 F1000.0 ; Cut to next point
G0 A56.571 ; Rotate Z for cutting direction
G1 X6.842 Y1.110 F1000.0 ; Cut to next point
G0 A60.506 ; Rotate Z for cutting direction
G1 X6.888 Y1.084 F1000.0 ; Cut to next point
G0 A64.599 ; Rotate Z for cutting direction
G1 X6.936 Y1.062 F1000.0 ; Cut to next point
G0 A68.636 ; Rotate Z for cutting direction
G1 X6.986 Y1.042 F1000.0 ; Cut to next point
G0 A72.653 ; Rotate Z for cutting direction
G1 X7.036 Y1.026 F1000.0 ; Cut to next point
G0 A76.762 ; Rotate Z for cutting direction
G1 X7.088 Y1.014 F1000.0 ; Cut to next point
G0 A80.794 ; Rotate Z for cutting direction
G1 X7.140 Y1.006 F1000.0 ; Cut to next point
G0 A84.820 ; Rotate Z for cutting direction
G1 X7.193 Y1.001 F1000.0 ; Cut to next point
G0 A88.864 ; Rotate Z for cutting direction
G1 X7.246 Y1.000 F1000.0 ; Cut to next point
G0 A92.936 ; Rotate Z for cutting direction
G1 X7.299 Y1.003 F1000.0 ; Cut to next point
G0 A96.983 ; Rotate Z for cutting direction
G1 X7.351 Y1.009 F1000.0 ; Cut to next point
G0 A101.004 ; Rotate Z for cutting direction
G1 X7.403 Y1.019 F1000.0 ; Cut to next point
G0 A105.072 ; Rotate Z for cutting direction
G1 X7.455 Y1.033 F1000.0 ; Cut to next point
G0 A109.163 ; Rotate Z for cutting direction
G1 X7.505 Y1.050 F1000.0 ; Cut to next point
G0 A113.172 ; Rotate Z for cutting direction
G1 X7.553 Y1.071 F1000.0 ; Cut to next point
G0 A117.235 ; Rotate Z for cutting direction
G1 X7.600 Y1.096 F1000.0 ; Cut to next point
G0 A121.258 ; Rotate Z for cutting direction
G1 X7.646 Y1.123 F1000.0 ; Cut to next point
G0 A125.297 ; Rotate Z for cutting direction
G1 X7.689 Y1.154 F1000.0 ; Cut to next point
G0 A129.370 ; Rotate Z for cutting direction
G1 X7.730 Y1.187 F1000.0 ; Cut to next point
G0 A133.419 ; Rotate Z for cutting direction
G1 X7.768 Y1.224 F1000.0 ; Cut to next point
G0 A137.477 ; Rotate Z for cutting direction
G1 X7.804 Y1.263 F1000.0 ; Cut to next point
G0 A141.502 ; Rotate Z for cutting direction
G1 X7.837 Y1.304 F1000.0 ; Cut to next point
G0 A145.551 ; Rotate Z for cutting direction
G1 X7.867 Y1.348 F1000.0 ; Cut to next point
G0 A149.624 ; Rotate Z for cutting direction
G1 X7.894 Y1.394 F1000.0 ; Cut to next point
G0 A153.686 ; Rotate Z for cutting direction
G1 X7.917 Y1.441 F1000.0 ; Cut to next point
G0 A157.740 ; Rotate Z for cutting direction
G1 X7.938 Y1.490 F1000.0 ; Cut to next point
G0 A161.775 ; Rotate Z for cutting direction
G1 X7.954 Y1.541 F1000.0 ; Cut to next point
G0 A165.819 ; Rotate Z for cutting direction
G1 X7.967 Y1.592 F1000.0 ; Cut to next point
G0 A169.853 ; Rotate Z for cutting direction
G1 X7.976 Y1.644 F1000.0 ; Cut to next point
G0 A173.895 ; Rotate Z for cutting direction
G1 X7.982 Y1.697 F1000.0 ; Cut to next point
G0 A177.968 ; Rotate Z for cutting direction
G1 X7.984 Y1.750 F1000.0 ; Cut to next point
G0 A182.013 ; Rotate Z for cutting direction
G1 X7.982 Y1.803 F1000.0 ; Cut to next point
G0 A186.059 ; Rotate Z for cutting direction
G1 X7.977 Y1.855 F1000.0 ; Cut to next point
G0 A190.106 ; Rotate Z for cutting direction
G1 X7.967 Y1.908 F1000.0 ; Cut to next point
G0 A194.156 ; Rotate Z for cutting direction
G1 X7.954 Y1.959 F1000.0 ; Cut to next point
G0 A198.210 ; Rotate Z for cutting direction
G1 X7.938 Y2.009 F1000.0 ; Cut to next point
G0 A202.260 ; Rotate Z for cutting direction
G1 X7.918 Y2.058 F1000.0 ; Cut to next point
G0 A206.245 ; Rotate Z for cutting direction
G1 X7.894 Y2.106 F1000.0 ; Cut to next point
G0 A210.674 ; Rotate Z for cutting direction
G1 X7.867 Y2.151 F1000.0 ; Cut to next point
G0 A213.771 ; Rotate Z for cutting direction
G1 X7.815 Y2.230 F1000.0 ; Cut to next point
G0 A214.008 ; Rotate Z for cutting direction
G1 X7.782 Y2.279 F1000.0 ; Cut to next point
G0 A213.982 ; Rotate Z for cutting direction
G1 X7.749 Y2.328 F1000.0 ; Cut to next point
G0 A213.941 ; Rotate Z for cutting direction
G1 X7.716 Y2.377 F1000.0 ; Cut to next point
G0 A213.888 ; Rotate Z for cutting direction
G1 X7.683 Y2.426 F1000.0 ; Cut to next point
G0 A213.820 ; Rotate Z for cutting direction
G1 X7.650 Y2.475 F1000.0 ; Cut to next point
G0 A213.740 ; Rotate Z for cutting direction
G1 X7.617 Y2.524 F1000.0 ; Cut to next point
G0 A213.645 ; Rotate Z for cutting direction
G1 X7.585 Y2.573 F1000.0 ; Cut to next point
G0 A213.538 ; Rotate Z for cutting direction
G1 X7.552 Y2.622 F1000.0 ; Cut to next point
G0 A213.416 ; Rotate Z for cutting direction
G1 X7.519 Y2.671 F1000.0 ; Cut to next point
G0 A213.282 ; Rotate Z for cutting direction
G1 X7.487 Y2.721 F1000.0 ; Cut to next point
G0 A213.133 ; Rotate Z for cutting direction
G1 X7.455 Y2.770 F1000.0 ; Cut to next point
G0 A212.972 ; Rotate Z for cutting direction
G1 X7.423 Y2.819 F1000.0 ; Cut to next point
G0 A212.796 ; Rotate Z for cutting direction
G1 X7.391 Y2.869 F1000.0 ; Cut to next point
G0 A212.608 ; Rotate Z for cutting direction
G1 X7.359 Y2.919 F1000.0 ; Cut to next point
G0 A212.405 ; Rotate Z for cutting direction
G1 X7.327 Y2.969 F1000.0 ; Cut to next point
G0 A212.190 ; Rotate Z for cutting direction
G1 X7.296 Y3.018 F1000.0 ; Cut to next point
G0 A211.960 ; Rotate Z for cutting direction
G1 X7.265 Y3.068 F1000.0 ; Cut to next point
G0 A211.718 ; Rotate Z for cutting direction
G1 X7.234 Y3.119 F1000.0 ; Cut to next point
G0 A211.461 ; Rotate Z for cutting direction
G1 X7.203 Y3.169 F1000.0 ; Cut to next point
G0 A211.192 ; Rotate Z for cutting direction
G1 X7.172 Y3.219 F1000.0 ; Cut to next point
G0 A210.920 ; Rotate Z for cutting direction
G1 X7.142 Y3.270 F1000.0 ; Cut to next point
G0 A210.679 ; Rotate Z for cutting direction
G1 X7.112 Y3.321 F1000.0 ; Cut to next point
G0 A210.474 ; Rotate Z for cutting direction
G1 X7.082 Y3.372 F1000.0 ; Cut to next point
G0 A210.293 ; Rotate Z for cutting direction
G1 X7.052 Y3.423 F1000.0 ; Cut to next point
G0 A210.111 ; Rotate Z for cutting direction
G1 X7.023 Y3.474 F1000.0 ; Cut to next point
G0 A209.924 ; Rotate Z for cutting direction
G1 X6.993 Y3.525 F1000.0 ; Cut to next point
G0 A209.731 ; Rotate Z for cutting direction
G1 X6.964 Y3.576 F1000.0 ; Cut to next point
G0 A209.535 ; Rotate Z for cutting direction
G1 X6.935 Y3.627 F1000.0 ; Cut to next point
G0 A209.338 ; Rotate Z for cutting direction
G1 X6.906 Y3.679 F1000.0 ; Cut to next point
G0 A209.141 ; Rotate Z for cutting direction
G1 X6.877 Y3.730 F1000.0 ; Cut to next point
G0 A208.944 ; Rotate Z for cutting direction
G1 X6.849 Y3.782 F1000.0 ; Cut to next point
G0 A208.748 ; Rotate Z for cutting direction
G1 X6.820 Y3.834 F1000.0 ; Cut to next point
G0 A208.552 ; Rotate Z for cutting direction
G1 X6.792 Y3.885 F1000.0 ; Cut to next point
G0 A208.356 ; Rotate Z for cutting direction
G1 X6.764 Y3.937 F1000.0 ; Cut to next point
G0 A208.161 ; Rotate Z for cutting direction
G1 X6.736 Y3.989 F1000.0 ; Cut to next point
G0 A207.965 ; Rotate Z for cutting direction
G1 X6.709 Y4.041 F1000.0 ; Cut to next point
G0 A207.770 ; Rotate Z for cutting direction
G1 X6.681 Y4.094 F1000.0 ; Cut to next point
G0 A207.575 ; Rotate Z for cutting direction
G1 X6.654 Y4.146 F1000.0 ; Cut to next point
G0 A207.380 ; Rotate Z for cutting direction
G1 X6.627 Y4.198 F1000.0 ; Cut to next point
G0 A207.186 ; Rotate Z for cutting direction
G1 X6.600 Y4.251 F1000.0 ; Cut to next point
G0 A206.991 ; Rotate Z for cutting direction
G1 X6.573 Y4.303 F1000.0 ; Cut to next point
G0 A206.797 ; Rotate Z for cutting direction
G1 X6.546 Y4.356 F1000.0 ; Cut to next point
G0 A206.603 ; Rotate Z for cutting direction
G1 X6.520 Y4.409 F1000.0 ; Cut to next point
G0 A206.409 ; Rotate Z for cutting direction
G1 X6.494 Y4.462 F1000.0 ; Cut to next point
G0 A206.215 ; Rotate Z for cutting direction
G1 X6.468 Y4.514 F1000.0 ; Cut to next point
G0 A206.020 ; Rotate Z for cutting direction
G1 X6.442 Y4.567 F1000.0 ; Cut to next point
G0 A205.825 ; Rotate Z for cutting direction
G1 X6.416 Y4.621 F1000.0 ; Cut to next point
G0 A205.630 ; Rotate Z for cutting direction
G1 X6.391 Y4.674 F1000.0 ; Cut to next point
G0 A205.435 ; Rotate Z for cutting direction
G1 X6.365 Y4.727 F1000.0 ; Cut to next point
G0 A205.240 ; Rotate Z for cutting direction
G1 X6.340 Y4.780 F1000.0 ; Cut to next point
G0 A205.045 ; Rotate Z for cutting direction
G1 X6.315 Y4.834 F1000.0 ; Cut to next point
G0 A204.850 ; Rotate Z for cutting direction
G1 X6.290 Y4.887 F1000.0 ; Cut to next point
G0 A204.655 ; Rotate Z for cutting direction
G1 X6.266 Y4.941 F1000.0 ; Cut to next point
G0 A204.461 ; Rotate Z for cutting direction
G1 X6.241 Y4.995 F1000.0 ; Cut to next point
G0 A204.266 ; Rotate Z for cutting direction
G1 X6.217 Y5.049 F1000.0 ; Cut to next point
G0 A204.071 ; Rotate Z for cutting direction
G1 X6.193 Y5.102 F1000.0 ; Cut to next point
G0 A203.876 ; Rotate Z for cutting direction
G1 X6.169 Y5.156 F1000.0 ; Cut to next point
G0 A203.681 ; Rotate Z for cutting direction
G1 X6.145 Y5.210 F1000.0 ; Cut to next point
G0 A203.486 ; Rotate Z for cutting direction
G1 X6.122 Y5.264 F1000.0 ; Cut to next point
G0 A203.292 ; Rotate Z for cutting direction
G1 X6.099 Y5.319 F1000.0 ; Cut to next point
G0 A203.097 ; Rotate Z for cutting direction
G1 X6.076 Y5.373 F1000.0 ; Cut to next point
G0 A202.902 ; Rotate Z for cutting direction
G1 X6.053 Y5.427 F1000.0 ; Cut to next point
G0 A202.707 ; Rotate Z for cutting direction
G1 X6.030 Y5.482 F1000.0 ; Cut to next point
G0 A202.512 ; Rotate Z for cutting direction
G1 X6.007 Y5.536 F1000.0 ; Cut to next point
G0 A202.317 ; Rotate Z for cutting direction
G1 X5.985 Y5.591 F1000.0 ; Cut to next point
G0 A202.122 ; Rotate Z for cutting direction
G1 X5.963 Y5.645 F1000.0 ; Cut to next point
G0 A201.928 ; Rotate Z for cutting direction
G1 X5.941 Y5.700 F1000.0 ; Cut to next point
G0 A201.733 ; Rotate Z for cutting direction
G1 X5.919 Y5.755 F1000.0 ; Cut to next point
G0 A201.538 ; Rotate Z for cutting direction
G1 X5.897 Y5.810 F1000.0 ; Cut to next point
G0 A201.343 ; Rotate Z for cutting direction
G1 X5.876 Y5.865 F1000.0 ; Cut to next point
G0 A201.148 ; Rotate Z for cutting direction
G1 X5.854 Y5.920 F1000.0 ; Cut to next point
G0 A200.953 ; Rotate Z for cutting direction
G1 X5.833 Y5.975 F1000.0 ; Cut to next point
G0 A200.759 ; Rotate Z for cutting direction
G1 X5.812 Y6.030 F1000.0 ; Cut to next point
G0 A200.564 ; Rotate Z for cutting direction
G1 X5.792 Y6.085 F1000.0 ; Cut to next point
G0 A200.369 ; Rotate Z for cutting direction
G1 X5.771 Y6.141 F1000.0 ; Cut to next point
G0 A200.174 ; Rotate Z for cutting direction
G1 X5.751 Y6.196 F1000.0 ; Cut to next point
G0 A199.979 ; Rotate Z for cutting direction
G1 X5.731 Y6.251 F1000.0 ; Cut to next point
G0 A199.784 ; Rotate Z for cutting direction
G1 X5.711 Y6.307 F1000.0 ; Cut to next point
G0 A199.590 ; Rotate Z for cutting direction
G1 X5.691 Y6.362 F1000.0 ; Cut to next point
G0 A199.395 ; Rotate Z for cutting direction
G1 X5.671 Y6.418 F1000.0 ; Cut to next point
G0 A199.200 ; Rotate Z for cutting direction
G1 X5.652 Y6.474 F1000.0 ; Cut to next point
G0 A199.005 ; Rotate Z for cutting direction
G1 X5.633 Y6.530 F1000.0 ; Cut to next point
G0 A198.810 ; Rotate Z for cutting direction
G1 X5.614 Y6.585 F1000.0 ; Cut to next point
G0 A198.616 ; Rotate Z for cutting direction
G1 X5.595 Y6.641 F1000.0 ; Cut to next point
G0 A198.421 ; Rotate Z for cutting direction
G1 X5.576 Y6.697 F1000.0 ; Cut to next point
G0 A198.226 ; Rotate Z for cutting direction
G1 X5.558 Y6.753 F1000.0 ; Cut to next point
G0 A198.031 ; Rotate Z for cutting direction
G1 X5.539 Y6.809 F1000.0 ; Cut to next point
G0 A197.836 ; Rotate Z for cutting direction
G1 X5.521 Y6.866 F1000.0 ; Cut to next point
G0 A197.641 ; Rotate Z for cutting direction
G1 X5.503 Y6.922 F1000.0 ; Cut to next point
G0 A197.446 ; Rotate Z for cutting direction
G1 X5.486 Y6.978 F1000.0 ; Cut to next point
G0 A197.251 ; Rotate Z for cutting direction
G1 X5.468 Y7.034 F1000.0 ; Cut to next point
G0 A197.056 ; Rotate Z for cutting direction
G1 X5.451 Y7.091 F1000.0 ; Cut to next point
G0 A196.861 ; Rotate Z for cutting direction
G1 X5.434 Y7.147 F1000.0 ; Cut to next point
G0 A196.666 ; Rotate Z for cutting direction
G1 X5.417 Y7.204 F1000.0 ; Cut to next point
G0 A196.471 ; Rotate Z for cutting direction
G1 X5.400 Y7.260 F1000.0 ; Cut to next point
G0 A196.276 ; Rotate Z for cutting direction
G1 X5.384 Y7.317 F1000.0 ; Cut to next point
G0 A196.082 ; Rotate Z for cutting direction
G1 X5.367 Y7.374 F1000.0 ; Cut to next point
G0 A195.887 ; Rotate Z for cutting direction
G1 X5.351 Y7.430 F1000.0 ; Cut to next point
G0 A195.692 ; Rotate Z for cutting direction
G1 X5.335 Y7.487 F1000.0 ; Cut to next point
G0 A195.497 ; Rotate Z for cutting direction
G1 X5.319 Y7.544 F1000.0 ; Cut to next point
G0 A195.302 ; Rotate Z for cutting direction
G1 X5.304 Y7.601 F1000.0 ; Cut to next point
G0 A195.107 ; Rotate Z for cutting direction
G1 X5.288 Y7.658 F1000.0 ; Cut to next point
G0 A194.913 ; Rotate Z for cutting direction
G1 X5.273 Y7.715 F1000.0 ; Cut to next point
G0 A194.718 ; Rotate Z for cutting direction
G1 X5.258 Y7.772 F1000.0 ; Cut to next point
G0 A194.523 ; Rotate Z for cutting direction
G1 X5.244 Y7.829 F1000.0 ; Cut to next point
G0 A194.328 ; Rotate Z for cutting direction
G1 X5.229 Y7.886 F1000.0 ; Cut to next point
G0 A194.134 ; Rotate Z for cutting direction
G1 X5.215 Y7.944 F1000.0 ; Cut to next point
G0 A193.939 ; Rotate Z for cutting direction
G1 X5.200 Y8.001 F1000.0 ; Cut to next point
G0 A193.744 ; Rotate Z for cutting direction
G1 X5.186 Y8.058 F1000.0 ; Cut to next point
G0 A193.549 ; Rotate Z for cutting direction
G1 X5.172 Y8.116 F1000.0 ; Cut to next point
G0 A193.355 ; Rotate Z for cutting direction
G1 X5.159 Y8.173 F1000.0 ; Cut to next point
G0 A193.160 ; Rotate Z for cutting direction
G1 X5.145 Y8.230 F1000.0 ; Cut to next point
G0 A192.965 ; Rotate Z for cutting direction
G1 X5.132 Y8.288 F1000.0 ; Cut to next point
G0 A192.770 ; Rotate Z for cutting direction
G1 X5.119 Y8.345 F1000.0 ; Cut to next point
G0 A192.575 ; Rotate Z for cutting direction
G1 X5.106 Y8.403 F1000.0 ; Cut to next point
G0 A192.381 ; Rotate Z for cutting direction
G1 X5.094 Y8.461 F1000.0 ; Cut to next point
G0 A192.186 ; Rotate Z for cutting direction
G1 X5.081 Y8.518 F1000.0 ; Cut to next point
G0 A191.991 ; Rotate Z for cutting direction
G1 X5.069 Y8.576 F1000.0 ; Cut to next point
G0 A191.796 ; Rotate Z for cutting direction
G1 X5.057 Y8.634 F1000.0 ; Cut to next point
G0 A191.601 ; Rotate Z for cutting direction
G1 X5.045 Y8.692 F1000.0 ; Cut to next point
G0 A191.406 ; Rotate Z for cutting direction
G1 X5.033 Y8.749 F1000.0 ; Cut to next point
G0 A191.211 ; Rotate Z for cutting direction
G1 X5.022 Y8.807 F1000.0 ; Cut to next point
G0 A191.016 ; Rotate Z for cutting direction
G1 X5.011 Y8.865 F1000.0 ; Cut to next point
G0 A190.821 ; Rotate Z for cutting direction
G1 X5.000 Y8.923 F1000.0 ; Cut to next point
G0 A190.626 ; Rotate Z for cutting direction
G1 X4.989 Y8.981 F1000.0 ; Cut to next point
G0 A190.431 ; Rotate Z for cutting direction
G1 X4.978 Y9.039 F1000.0 ; Cut to next point
G0 A190.236 ; Rotate Z for cutting direction
G1 X4.967 Y9.097 F1000.0 ; Cut to next point
G0 A190.041 ; Rotate Z for cutting direction
G1 X4.957 Y9.155 F1000.0 ; Cut to next point
G0 A189.846 ; Rotate Z for cutting direction
G1 X4.947 Y9.213 F1000.0 ; Cut to next point
G0 A189.652 ; Rotate Z for cutting direction
G1 X4.937 Y9.271 F1000.0 ; Cut to next point
G0 A189.457 ; Rotate Z for cutting direction
G1 X4.928 Y9.330 F1000.0 ; Cut to next point
G0 A189.262 ; Rotate Z for cutting direction
G1 X4.918 Y9.388 F1000.0 ; Cut to next point
G0 A189.067 ; Rotate Z for cutting direction
G1 X4.909 Y9.446 F1000.0 ; Cut to next point
G0 A188.873 ; Rotate Z for cutting direction
G1 X4.900 Y9.504 F1000.0 ; Cut to next point
G0 A188.678 ; Rotate Z for cutting direction
G1 X4.891 Y9.563 F1000.0 ; Cut to next point
G0 A188.483 ; Rotate Z for cutting direction
G1 X4.882 Y9.621 F1000.0 ; Cut to next point
G0 A188.288 ; Rotate Z for cutting direction
G1 X4.874 Y9.679 F1000.0 ; Cut to next point
G0 A188.093 ; Rotate Z for cutting direction
G1 X4.865 Y9.738 F1000.0 ; Cut to next point
G0 A187.899 ; Rotate Z for cutting direction
G1 X4.857 Y9.796 F1000.0 ; Cut to next point
G0 A187.704 ; Rotate Z for cutting direction
G1 X4.849 Y9.855 F1000.0 ; Cut to next point
G0 A187.508 ; Rotate Z for cutting direction
G1 X4.841 Y9.913 F1000.0 ; Cut to next point
G0 A187.313 ; Rotate Z for cutting direction
G1 X4.834 Y9.972 F1000.0 ; Cut to next point
G0 A187.118 ; Rotate Z for cutting direction
G1 X4.827 Y10.030 F1000.0 ; Cut to next point
G0 A186.924 ; Rotate Z for cutting direction
G1 X4.820 Y10.089 F1000.0 ; Cut to next point
G0 A186.732 ; Rotate Z for cutting direction
G1 X4.813 Y10.147 F1000.0 ; Cut to next point
G0 A186.541 ; Rotate Z for cutting direction
G1 X4.806 Y10.206 F1000.0 ; Cut to next point
G0 A186.349 ; Rotate Z for cutting direction
G1 X4.799 Y10.265 F1000.0 ; Cut to next point
G0 A186.156 ; Rotate Z for cutting direction
G1 X4.793 Y10.323 F1000.0 ; Cut to next point
G0 A185.963 ; Rotate Z for cutting direction
G1 X4.787 Y10.382 F1000.0 ; Cut to next point
G0 A185.769 ; Rotate Z for cutting direction
G1 X4.781 Y10.441 F1000.0 ; Cut to next point
G0 A185.574 ; Rotate Z for cutting direction
G1 X4.775 Y10.499 F1000.0 ; Cut to next point
G0 A185.379 ; Rotate Z for cutting direction
G1 X4.770 Y10.558 F1000.0 ; Cut to next point
G0 A185.184 ; Rotate Z for cutting direction
G1 X4.764 Y10.617 F1000.0 ; Cut to next point
G0 A184.987 ; Rotate Z for cutting direction
G1 X4.759 Y10.676 F1000.0 ; Cut to next point
G0 A184.790 ; Rotate Z for cutting direction
G1 X4.754 Y10.735 F1000.0 ; Cut to next point
G0 A184.593 ; Rotate Z for cutting direction
G1 X4.750 Y10.793 F1000.0 ; Cut to next point
G0 A184.395 ; Rotate Z for cutting direction
G1 X4.745 Y10.852 F1000.0 ; Cut to next point
G0 A184.196 ; Rotate Z for cutting direction
G1 X4.741 Y10.911 F1000.0 ; Cut to next point
G0 A183.997 ; Rotate Z for cutting direction
G1 X4.737 Y10.970 F1000.0 ; Cut to next point
G0 A183.796 ; Rotate Z for cutting direction
G1 X4.733 Y11.029 F1000.0 ; Cut to next point
G0 A183.596 ; Rotate Z for cutting direction
G1 X4.729 Y11.088 F1000.0 ; Cut to next point
G0 A183.394 ; Rotate Z for cutting direction
G1 X4.726 Y11.147 F1000.0 ; Cut to next point
G0 A183.192 ; Rotate Z for cutting direction
G1 X4.722 Y11.205 F1000.0 ; Cut to next point
G0 A182.990 ; Rotate Z for cutting direction
G1 X4.719 Y11.264 F1000.0 ; Cut to next point
G0 A182.799 ; Rotate Z for cutting direction
G1 X4.716 Y11.323 F1000.0 ; Cut to next point
G0 A183.101 ; Rotate Z for cutting direction
G1 X4.711 Y11.419 F1000.0 ; Cut to next point
G0 A183.383 ; Rotate Z for cutting direction
G1 X4.708 Y11.476 F1000.0 ; Cut to next point
G0 A183.402 ; Rotate Z for cutting direction
G1 X4.704 Y11.533 F1000.0 ; Cut to next point
G0 A183.432 ; Rotate Z for cutting direction
G1 X4.701 Y11.589 F1000.0 ; Cut to next point
G0 A183.472 ; Rotate Z for cutting direction
G1 X4.698 Y11.646 F1000.0 ; Cut to next point
G0 A183.522 ; Rotate Z for cutting direction
G1 X4.694 Y11.703 F1000.0 ; Cut to next point
G0 A183.582 ; Rotate Z for cutting direction
G1 X4.691 Y11.760 F1000.0 ; Cut to next point
G0 A183.652 ; Rotate Z for cutting direction
G1 X4.687 Y11.816 F1000.0 ; Cut to next point
G0 A183.731 ; Rotate Z for cutting direction
G1 X4.683 Y11.873 F1000.0 ; Cut to next point
G0 A183.821 ; Rotate Z for cutting direction
G1 X4.679 Y11.930 F1000.0 ; Cut to next point
G0 A183.921 ; Rotate Z for cutting direction
G1 X4.676 Y11.986 F1000.0 ; Cut to next point
G0 A184.030 ; Rotate Z for cutting direction
G1 X4.672 Y12.043 F1000.0 ; Cut to next point
G0 A184.150 ; Rotate Z for cutting direction
G1 X4.667 Y12.100 F1000.0 ; Cut to next point
G0 A184.280 ; Rotate Z for cutting direction
G1 X4.663 Y12.157 F1000.0 ; Cut to next point
G0 A184.419 ; Rotate Z for cutting direction
G1 X4.659 Y12.213 F1000.0 ; Cut to next point
G0 A184.569 ; Rotate Z for cutting direction
G1 X4.654 Y12.270 F1000.0 ; Cut to next point
G0 A184.728 ; Rotate Z for cutting direction
G1 X4.650 Y12.326 F1000.0 ; Cut to next point
G0 A184.898 ; Rotate Z for cutting direction
G1 X4.645 Y12.383 F1000.0 ; Cut to next point
G0 A185.077 ; Rotate Z for cutting direction
G1 X4.640 Y12.440 F1000.0 ; Cut to next point
G0 A185.263 ; Rotate Z for cutting direction
G1 X4.635 Y12.496 F1000.0 ; Cut to next point
G0 A185.447 ; Rotate Z for cutting direction
G1 X4.629 Y12.553 F1000.0 ; Cut to next point
G0 A185.626 ; Rotate Z for cutting direction
G1 X4.624 Y12.609 F1000.0 ; Cut to next point
G0 A185.801 ; Rotate Z for cutting direction
G1 X4.618 Y12.666 F1000.0 ; Cut to next point
G0 A185.972 ; Rotate Z for cutting direction
G1 X4.612 Y12.722 F1000.0 ; Cut to next point
G0 A186.139 ; Rotate Z for cutting direction
G1 X4.606 Y12.779 F1000.0 ; Cut to next point
G0 A186.301 ; Rotate Z for cutting direction
G1 X4.600 Y12.835 F1000.0 ; Cut to next point
G0 A186.460 ; Rotate Z for cutting direction
G1 X4.593 Y12.892 F1000.0 ; Cut to next point
G0 A186.614 ; Rotate Z for cutting direction
G1 X4.587 Y12.948 F1000.0 ; Cut to next point
G0 A186.764 ; Rotate Z for cutting direction
G1 X4.580 Y13.005 F1000.0 ; Cut to next point
G0 A186.910 ; Rotate Z for cutting direction
G1 X4.573 Y13.061 F1000.0 ; Cut to next point
G0 A187.052 ; Rotate Z for cutting direction
G1 X4.566 Y13.118 F1000.0 ; Cut to next point
G0 A187.190 ; Rotate Z for cutting direction
G1 X4.559 Y13.174 F1000.0 ; Cut to next point
G0 A187.324 ; Rotate Z for cutting direction
G1 X4.552 Y13.230 F1000.0 ; Cut to next point
G0 A187.454 ; Rotate Z for cutting direction
G1 X4.544 Y13.287 F1000.0 ; Cut to next point
G0 A187.584 ; Rotate Z for cutting direction
G1 X4.537 Y13.343 F1000.0 ; Cut to next point
G0 A187.717 ; Rotate Z for cutting direction
G1 X4.529 Y13.399 F1000.0 ; Cut to next point
G0 A187.852 ; Rotate Z for cutting direction
G1 X4.521 Y13.456 F1000.0 ; Cut to next point
G0 A187.991 ; Rotate Z for cutting direction
G1 X4.514 Y13.512 F1000.0 ; Cut to next point
G0 A188.132 ; Rotate Z for cutting direction
G1 X4.506 Y13.568 F1000.0 ; Cut to next point
G0 A188.276 ; Rotate Z for cutting direction
G1 X4.497 Y13.624 F1000.0 ; Cut to next point
G0 A188.421 ; Rotate Z for cutting direction
G1 X4.489 Y13.681 F1000.0 ; Cut to next point
G0 A188.566 ; Rotate Z for cutting direction
G1 X4.481 Y13.737 F1000.0 ; Cut to next point
G0 A188.711 ; Rotate Z for cutting direction
G1 X4.472 Y13.793 F1000.0 ; Cut to next point
G0 A188.857 ; Rotate Z for cutting direction
G1 X4.463 Y13.849 F1000.0 ; Cut to next point
G0 A189.002 ; Rotate Z for cutting direction
G1 X4.454 Y13.905 F1000.0 ; Cut to next point
G0 A189.147 ; Rotate Z for cutting direction
G1 X4.445 Y13.961 F1000.0 ; Cut to next point
G0 A189.292 ; Rotate Z for cutting direction
G1 X4.436 Y14.018 F1000.0 ; Cut to next point
G0 A189.437 ; Rotate Z for cutting direction
G1 X4.427 Y14.074 F1000.0 ; Cut to next point
G0 A189.582 ; Rotate Z for cutting direction
G1 X4.417 Y14.130 F1000.0 ; Cut to next point
G0 A189.727 ; Rotate Z for cutting direction
G1 X4.408 Y14.186 F1000.0 ; Cut to next point
G0 A189.873 ; Rotate Z for cutting direction
G1 X4.398 Y14.242 F1000.0 ; Cut to next point
G0 A190.018 ; Rotate Z for cutting direction
G1 X4.388 Y14.298 F1000.0 ; Cut to next point
G0 A190.163 ; Rotate Z for cutting direction
G1 X4.378 Y14.354 F1000.0 ; Cut to next point
G0 A190.308 ; Rotate Z for cutting direction
G1 X4.368 Y14.409 F1000.0 ; Cut to next point
G0 A190.454 ; Rotate Z for cutting direction
G1 X4.358 Y14.465 F1000.0 ; Cut to next point
G0 A190.599 ; Rotate Z for cutting direction
G1 X4.347 Y14.521 F1000.0 ; Cut to next point
G0 A190.744 ; Rotate Z for cutting direction
G1 X4.337 Y14.577 F1000.0 ; Cut to next point
G0 A190.890 ; Rotate Z for cutting direction
G1 X4.326 Y14.633 F1000.0 ; Cut to next point
G0 A191.035 ; Rotate Z for cutting direction
G1 X4.315 Y14.689 F1000.0 ; Cut to next point
G0 A191.180 ; Rotate Z for cutting direction
G1 X4.304 Y14.744 F1000.0 ; Cut to next point
G0 A191.325 ; Rotate Z for cutting direction
G1 X4.293 Y14.800 F1000.0 ; Cut to next point
G0 A191.468 ; Rotate Z for cutting direction
G1 X4.281 Y14.856 F1000.0 ; Cut to next point
G0 A191.609 ; Rotate Z for cutting direction
G1 X4.270 Y14.911 F1000.0 ; Cut to next point
G0 A191.746 ; Rotate Z for cutting direction
G1 X4.258 Y14.967 F1000.0 ; Cut to next point
G0 A191.882 ; Rotate Z for cutting direction
G1 X4.247 Y15.023 F1000.0 ; Cut to next point
G0 A192.014 ; Rotate Z for cutting direction
G1 X4.235 Y15.078 F1000.0 ; Cut to next point
G0 A192.144 ; Rotate Z for cutting direction
G1 X4.223 Y15.134 F1000.0 ; Cut to next point
G0 A192.275 ; Rotate Z for cutting direction
G1 X4.211 Y15.189 F1000.0 ; Cut to next point
G0 A192.409 ; Rotate Z for cutting direction
G1 X4.199 Y15.245 F1000.0 ; Cut to next point
G0 A192.547 ; Rotate Z for cutting direction
G1 X4.186 Y15.300 F1000.0 ; Cut to next point
G0 A192.690 ; Rotate Z for cutting direction
G1 X4.174 Y15.356 F1000.0 ; Cut to next point
G0 A192.837 ; Rotate Z for cutting direction
G1 X4.161 Y15.411 F1000.0 ; Cut to next point
G0 A192.988 ; Rotate Z for cutting direction
G1 X4.148 Y15.467 F1000.0 ; Cut to next point
G0 A193.143 ; Rotate Z for cutting direction
G1 X4.136 Y15.522 F1000.0 ; Cut to next point
G0 A193.303 ; Rotate Z for cutting direction
G1 X4.122 Y15.577 F1000.0 ; Cut to next point
G0 A193.467 ; Rotate Z for cutting direction
G1 X4.109 Y15.633 F1000.0 ; Cut to next point
G0 A193.635 ; Rotate Z for cutting direction
G1 X4.096 Y15.688 F1000.0 ; Cut to next point
G0 A193.808 ; Rotate Z for cutting direction
G1 X4.082 Y15.743 F1000.0 ; Cut to next point
G0 A193.984 ; Rotate Z for cutting direction
G1 X4.069 Y15.798 F1000.0 ; Cut to next point
G0 A194.166 ; Rotate Z for cutting direction
G1 X4.055 Y15.853 F1000.0 ; Cut to next point
G0 A194.351 ; Rotate Z for cutting direction
G1 X4.041 Y15.908 F1000.0 ; Cut to next point
G0 A194.536 ; Rotate Z for cutting direction
G1 X4.026 Y15.963 F1000.0 ; Cut to next point
G0 A194.713 ; Rotate Z for cutting direction
G1 X4.012 Y16.018 F1000.0 ; Cut to next point
G0 A194.880 ; Rotate Z for cutting direction
G1 X3.997 Y16.073 F1000.0 ; Cut to next point
G0 A195.037 ; Rotate Z for cutting direction
G1 X3.982 Y16.128 F1000.0 ; Cut to next point
G0 A195.185 ; Rotate Z for cutting direction
G1 X3.968 Y16.183 F1000.0 ; Cut to next point
G0 A195.322 ; Rotate Z for cutting direction
G1 X3.953 Y16.238 F1000.0 ; Cut to next point
G0 A195.450 ; Rotate Z for cutting direction
G1 X3.937 Y16.292 F1000.0 ; Cut to next point
G0 A195.568 ; Rotate Z for cutting direction
G1 X3.922 Y16.347 F1000.0 ; Cut to next point
G0 A195.676 ; Rotate Z for cutting direction
G1 X3.907 Y16.402 F1000.0 ; Cut to next point
G0 A195.774 ; Rotate Z for cutting direction
G1 X3.891 Y16.457 F1000.0 ; Cut to next point
G0 A195.862 ; Rotate Z for cutting direction
G1 X3.876 Y16.511 F1000.0 ; Cut to next point
G0 A195.941 ; Rotate Z for cutting direction
G1 X3.860 Y16.566 F1000.0 ; Cut to next point
G0 A196.010 ; Rotate Z for cutting direction
G1 X3.845 Y16.621 F1000.0 ; Cut to next point
G0 A196.069 ; Rotate Z for cutting direction
G1 X3.829 Y16.675 F1000.0 ; Cut to next point
G0 A196.118 ; Rotate Z for cutting direction
G1 X3.813 Y16.730 F1000.0 ; Cut to next point
G0 A196.157 ; Rotate Z for cutting direction
G1 X3.797 Y16.784 F1000.0 ; Cut to next point
G0 A196.186 ; Rotate Z for cutting direction
G1 X3.781 Y16.839 F1000.0 ; Cut to next point
G0 A196.206 ; Rotate Z for cutting direction
G1 X3.766 Y16.894 F1000.0 ; Cut to next point
G0 A196.216 ; Rotate Z for cutting direction
G1 X3.750 Y16.948 F1000.0 ; Cut to next point
G0 Z-0.5 ; Raise Z for corner
G0 A-89.119 ; Rotate Z for corner
G0 Z-1.0 ; Lower Z to cutting height
G0 X3.695 Y16.947 ; Move to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.640 Y16.946 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.585 Y16.946 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.530 Y16.945 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.475 Y16.944 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.420 Y16.943 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.365 Y16.942 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X3.310 Y16.941 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X3.255 Y16.940 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X3.200 Y16.940 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X3.145 Y16.939 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X3.090 Y16.938 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X3.035 Y16.937 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.980 Y16.936 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.925 Y16.935 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.870 Y16.935 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.815 Y16.934 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.760 Y16.933 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.705 Y16.932 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.650 Y16.931 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.595 Y16.930 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.540 Y16.929 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.485 Y16.929 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.430 Y16.928 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.375 Y16.927 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.320 Y16.926 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.265 Y16.925 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.210 Y16.924 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.155 Y16.924 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.100 Y16.923 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X2.045 Y16.922 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.990 Y16.921 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.935 Y16.920 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.880 Y16.919 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.825 Y16.918 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.770 Y16.918 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.715 Y16.917 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.660 Y16.916 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.605 Y16.915 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.550 Y16.914 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.495 Y16.913 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.440 Y16.913 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.385 Y16.912 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.330 Y16.911 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.275 Y16.910 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.220 Y16.909 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.165 Y16.908 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.110 Y16.907 F1000.0 ; Cut to next point
G0 A-89.118 ; Rotate Z for cutting direction
G1 X1.055 Y16.907 F1000.0 ; Cut to next point
G0 A-89.119 ; Rotate Z for cutting direction
G1 X1.000 Y16.906 F1000.0 ; Cut to next point
G0 Z-0.5 ; Raise tool to safe height


G28 ; Home all axes
M2 ; End program